### ISSUE TITLE
No such file or directory: 'ANN_DIR.mat'

### ISSUE THREAD

**Issue by guissart** [littleaich/heatmap-regulation#1]
Hello
I am trying to execute your code in the folder `vgg-cells` but it seams that this file is missing.
```
python main_simple.py --img-dir 'TRAIN_IMG_DIR' --ann-dir 'ANN_DIR' --arch 'vgg16' --optim 'adam' 
--workers 4 --batch-size 32 --start-epoch 1 --end-epoch 100 --learning-rate 0.00001 --momentum 0.9 
--weight-decay 0.00001 --save-interval 1 --print-freq 20
```
with the error :

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 33, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: 'ANN_DIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_simple.py", line 434, in <module>
    main();
  File "main_simple.py", line 152, in main
    transforms.Normalize(mean=mean, std=std),
  File "/srv/heatmap-regulation/vgg-cells/datasets_cells.py", line 192, in __init__
    imgs = make_dataset(img_dir, gam_dir, ann_dir);
  File "/srv/heatmap-regulation/vgg-cells/datasets_cells.py", line 30, in make_dataset
    count_all = np.squeeze(scipy.io.loadmat(ann_dir)['count_gt'].astype('i2'));
  File "/opt/conda/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/opt/conda/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: 'ANN_DIR.mat'
```

**Comment by shubhraaich** [comment]
Hi guissart,

you need to download the dataset and replace "TRAIN_IMG_DIR", "ANN_DIR", "GAM_DIR", and "TEST_IMG_DIR" with the corresponding directories containing trianing images, annotation files, gam files, and test images, respectively. Those directory names in all uppercase letters are just placeholders for specific directory names.

Also, I have added the (train-val)-test and then (train-val) splitting codes in the repo. Please run the initial preprocessing files in the order changing the relative directory path ("base_path") in your local machine. Then, with the mean and std saved for particular datasets, run the training code.

**Comment by Ampatishan** [comment]
hello 

In the main_simple.py there is a line import datasets_ccsjtu, but there is no datasets_ccsjtu.py in the folder. how to import datasets_ccsjtu
![image](https://user-images.githubusercontent.com/28345872/47899897-05033f80-dea1-11e8-8b6a-b14ed970cb5e.png)

**Comment by shubhraaich** [comment]
Hi @Ampatishan 
Please check the updated code directory which is much better documented. Thanks.
