### ISSUE TITLE
Resize image to 224*224

### ISSUE THREAD

**Issue by ciampluca** [littleaich/heatmap-regulation#3]
Hello,
I'm trying to run your code in folder carpk_pucpr .
I think that input images must be resized to 224x224 .... is it correct?

**Comment by ciampluca** [comment]
At least in the file main_simple

**Comment by shubhraaich** [comment]
Hi @ciampluca ,

No, the model runs on full image size, except for CARPK & PUCPR+ datasets, I resize the images into half as described in the paper https://arxiv.org/abs/1803.05494.
Anyway, I am planning to update the readme with detailed instructions. Please allow me 2/3 days for that. Please check back this repo on Friday afternoon or Satday morning with updated instructions.

**Comment by ciampluca** [comment]
ok thanks
please check also (for CARPK & PUCPR+ dataset) if exists the mean and the std (because mean and std of ImageNet are commented)

**Comment by shubhraaich** [comment]
Hi @ciampluca 

The repo is updated with detailed instructions. Please let me know in case of further confusions.
