### ISSUE TITLE
Not able to reproduce the results on CARPK Dataset

### ISSUE THREAD

**Issue by akshitac8** [littleaich/heatmap-regulation#4]
Hello,
I ran the testing code on CARPK dataset with both HR and simple pre-trained model and got completely different results.
```
HR Model
MAE(absolute) = 30.0
RMSE(absolute) = 33.1692366068
```
```
Simple Model
MAE(absolute) = 23.84375
RMSE(absolute) = 27.764964365
```

Are there some other settings that I missed?

**Comment by shubhraaich** [comment]
Hi @akshitac8 
Although you have closed the issue, I would be interested to know what gave you the different results.
